<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.525">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>Advanced Statistics - Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script><script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script><script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script><link rel="stylesheet" href="styles.css">
</head>
<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="navbar navbar-expand-lg " data-bs-theme="dark"><div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Advanced Statistics</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
<li class="nav-item">
    <a class="nav-link" href="./review.html"> 
<span class="menu-text">Basic Review</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./confidence_intervals.html"> 
<span class="menu-text">Confidence Intervals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./statistical_hypotheses.html"> 
<span class="menu-text">Statistical Hypotheses</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./linear_regression.html" aria-current="page"> 
<span class="menu-text">Linear Regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./diagnostics.html"> 
<span class="menu-text">Diagnostics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./anova_categorical.html"> 
<span class="menu-text">ANOVA for Categorical</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./model_selection.html"> 
<span class="menu-text">Model Selection</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./bayes_nets.html"> 
<span class="menu-text">Bayesian Networks</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./glm.html"> 
<span class="menu-text">Generalized Linear Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./gam.html"> 
<span class="menu-text">Generalized Additive Models</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./significant_results.html"> 
<span class="menu-text">Significant Results</span></a>
  </li>  
</ul>
<ul class="navbar-nav navbar-nav-scroll ms-auto">
<li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">
<li>
    <a class="dropdown-item" href="https://github.com/clickityKlein/Statistics">
 <span class="dropdown-text">Source Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/clickityKlein">
 <span class="dropdown-text">Carl Klein’s Main Page</span></a>
  </li>  
    </ul>
</li>
</ul>
</div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li>
<a href="#simple-linear-regression" id="toc-simple-linear-regression" class="nav-link active" data-scroll-target="#simple-linear-regression">Simple Linear Regression</a>
  <ul class="collapse">
<li><a href="#the-expected-value-of-the-response-variable" id="toc-the-expected-value-of-the-response-variable" class="nav-link" data-scroll-target="#the-expected-value-of-the-response-variable">The Expected Value of the Response Variable</a></li>
  <li><a href="#interpreting-parameters" id="toc-interpreting-parameters" class="nav-link" data-scroll-target="#interpreting-parameters">Interpreting Parameters</a></li>
  <li><a href="#minimizing-the-residuals" id="toc-minimizing-the-residuals" class="nav-link" data-scroll-target="#minimizing-the-residuals">Minimizing the Residuals</a></li>
  <li><a href="#how-we-find-the-parameter-estimates" id="toc-how-we-find-the-parameter-estimates" class="nav-link" data-scroll-target="#how-we-find-the-parameter-estimates">How we Find the Parameter Estimates?</a></li>
  <li><a href="#estimating-the-variance" id="toc-estimating-the-variance" class="nav-link" data-scroll-target="#estimating-the-variance">Estimating the Variance</a></li>
  <li><a href="#coefficient-of-determination" id="toc-coefficient-of-determination" class="nav-link" data-scroll-target="#coefficient-of-determination">Coefficient of Determination</a></li>
  <li><a href="#slope-distribution" id="toc-slope-distribution" class="nav-link" data-scroll-target="#slope-distribution">Slope Distribution</a></li>
  <li>
<a href="#summary-of-slr" id="toc-summary-of-slr" class="nav-link" data-scroll-target="#summary-of-slr">SUMMARY OF SLR</a>
  <ul class="collapse">
<li><a href="#main-formula" id="toc-main-formula" class="nav-link" data-scroll-target="#main-formula">Main Formula</a></li>
  <li><a href="#variance-slope-distribution-betas" id="toc-variance-slope-distribution-betas" class="nav-link" data-scroll-target="#variance-slope-distribution-betas">Variance &amp; Slope Distribution (<span class="math inline">\(\beta\)</span>s)</a></li>
  <li><a href="#ci-for-t-tests-on-beta" id="toc-ci-for-t-tests-on-beta" class="nav-link" data-scroll-target="#ci-for-t-tests-on-beta">CI for t-tests on <span class="math inline">\(\beta\)</span></a></li>
  <li><a href="#coefficient-of-determination-1" id="toc-coefficient-of-determination-1" class="nav-link" data-scroll-target="#coefficient-of-determination-1">Coefficient of Determination</a></li>
  </ul>
</li>
  <li><a href="#workflow-for-simple-linear-regression" id="toc-workflow-for-simple-linear-regression" class="nav-link" data-scroll-target="#workflow-for-simple-linear-regression">Workflow for Simple Linear Regression</a></li>
  <li><a href="#simple-linear-regression-in-r" id="toc-simple-linear-regression-in-r" class="nav-link" data-scroll-target="#simple-linear-regression-in-r">Simple Linear Regression in R</a></li>
  </ul>
</li>
  <li>
<a href="#multiple-linear-regression" id="toc-multiple-linear-regression" class="nav-link" data-scroll-target="#multiple-linear-regression">Multiple Linear Regression</a>
  <ul class="collapse">
<li><a href="#matrix-algebra-applications-solutions" id="toc-matrix-algebra-applications-solutions" class="nav-link" data-scroll-target="#matrix-algebra-applications-solutions">Matrix Algebra Applications &amp; Solutions</a></li>
  <li><a href="#interpreting-mlr" id="toc-interpreting-mlr" class="nav-link" data-scroll-target="#interpreting-mlr">Interpreting MLR</a></li>
  <li>
<a href="#quantifying-goodness-of-fit" id="toc-quantifying-goodness-of-fit" class="nav-link" data-scroll-target="#quantifying-goodness-of-fit">Quantifying Goodness of Fit</a>
  <ul class="collapse">
<li><a href="#r2-vs.-r_a2" id="toc-r2-vs.-r_a2" class="nav-link" data-scroll-target="#r2-vs.-r_a2"><span class="math inline">\(R^2\)</span> vs.&nbsp;<span class="math inline">\(R_a^2\)</span></a></li>
  <li><a href="#covariance-correlation" id="toc-covariance-correlation" class="nav-link" data-scroll-target="#covariance-correlation">Covariance &amp; Correlation</a></li>
  </ul>
</li>
  <li>
<a href="#individual-t-tests" id="toc-individual-t-tests" class="nav-link" data-scroll-target="#individual-t-tests">Individual t-tests</a>
  <ul class="collapse">
<li><a href="#mlr-in-r-individual-t-test-output-from-summary" id="toc-mlr-in-r-individual-t-test-output-from-summary" class="nav-link" data-scroll-target="#mlr-in-r-individual-t-test-output-from-summary">MLR in R: Individual t-test Output from <code>summary</code></a></li>
  <li><a href="#type-i-errors-in-multiple-t-tests" id="toc-type-i-errors-in-multiple-t-tests" class="nav-link" data-scroll-target="#type-i-errors-in-multiple-t-tests">Type I Errors in Multiple t-tests</a></li>
  </ul>
</li>
  <li><a href="#multicollinearity-collinearity-non-identifiability" id="toc-multicollinearity-collinearity-non-identifiability" class="nav-link" data-scroll-target="#multicollinearity-collinearity-non-identifiability">Multicollinearity / Collinearity / Non-Identifiability</a></li>
  <li>
<a href="#f-test" id="toc-f-test" class="nav-link" data-scroll-target="#f-test">F-test</a>
  <ul class="collapse">
<li><a href="#the-full-f-test" id="toc-the-full-f-test" class="nav-link" data-scroll-target="#the-full-f-test">The Full F-test</a></li>
  <li><a href="#the-partial-f-test" id="toc-the-partial-f-test" class="nav-link" data-scroll-target="#the-partial-f-test">The Partial F-test</a></li>
  </ul>
</li>
  <li>
<a href="#feature-selection" id="toc-feature-selection" class="nav-link" data-scroll-target="#feature-selection">Feature Selection</a>
  <ul class="collapse">
<li><a href="#forward-selection" id="toc-forward-selection" class="nav-link" data-scroll-target="#forward-selection">Forward Selection</a></li>
  <li><a href="#backward-selection" id="toc-backward-selection" class="nav-link" data-scroll-target="#backward-selection">Backward Selection</a></li>
  </ul>
</li>
  </ul>
</li>
  <li>
<a href="#further-interpretations-and-r-examples" id="toc-further-interpretations-and-r-examples" class="nav-link" data-scroll-target="#further-interpretations-and-r-examples">Further Interpretations and R Examples</a>
  <ul class="collapse">
<li><a href="#basic-interpretations" id="toc-basic-interpretations" class="nav-link" data-scroll-target="#basic-interpretations">Basic Interpretations</a></li>
  <li><a href="#f-tests" id="toc-f-tests" class="nav-link" data-scroll-target="#f-tests">F-tests</a></li>
  </ul>
</li>
  </ul></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title">Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header><p>This page features information about creating and interpreting regression models.</p>
<ul>
<li>Simple Linear Regression (math, programming, and interpretation)</li>
<li>Multiple Linear Regression (math, programming, and interpretation)</li>
</ul>
<hr>
<section id="simple-linear-regression" class="level1"><h1>Simple Linear Regression</h1>
<p>The goal of simple linear regression is to figure out an equation of a line through the data in an attempt to find the relationship between feature and response to predict future values. The equation is of the form:</p>
<p><span class="math inline">\(y_i = \alpha + \beta x_i + \epsilon_i\)</span></p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span> is the prediction at <span class="math inline">\(x_i\)</span>
</li>
<li>
<span class="math inline">\(\alpha\)</span> is the “y-intercept”</li>
<li>
<span class="math inline">\(\beta\)</span> is the “slope”</li>
<li>
<span class="math inline">\(\epsilon_i \sim N(0, \sigma^2)\)</span>, and each are independent</li>
</ul>
<p>In vector (or set) form:</p>
<p><span class="math inline">\(Y = \alpha + \beta X + \epsilon\)</span></p>
<p>where</p>
<ul>
<li>
<span class="math inline">\(X\)</span>: the independent variable, the predictor, the explanatory variable, the feature</li>
<li>
<span class="math inline">\(Y\)</span>: the dependent variable, the response variable</li>
<li>
<span class="math inline">\(\epsilon\)</span>: the random deviation, random error – accounts for the fact that the world is uncertain and that there are random deviations around the true process.</li>
</ul>
<section id="the-expected-value-of-the-response-variable" class="level2"><h2 class="anchored" data-anchor-id="the-expected-value-of-the-response-variable">The Expected Value of the Response Variable</h2>
<p>Given <span class="math inline">\(Y = \alpha + \beta X + \epsilon\)</span>, what is <span class="math inline">\(E[Y]\)</span>?</p>
<p><span class="math inline">\(E[Y] = E[\alpha + \beta X + \epsilon]\)</span></p>
<p><span class="math inline">\(= E[\alpha] + E[\beta X] + E[\epsilon]\)</span></p>
<p><span class="math inline">\(= \alpha + \beta E[X] + 0\)</span></p>
<p><span class="math inline">\(= \alpha + \beta X\)</span></p>
</section><section id="interpreting-parameters" class="level2"><h2 class="anchored" data-anchor-id="interpreting-parameters">Interpreting Parameters</h2>
<p><span class="math inline">\(\beta\)</span>: the slope of our true regression line represents the increase in our response from a unit increase in our feature.</p>
</section><section id="minimizing-the-residuals" class="level2"><h2 class="anchored" data-anchor-id="minimizing-the-residuals">Minimizing the Residuals</h2>
<p>Given our data, <span class="math inline">\((x_1, y_1), \dots, (x_n, y_n)\)</span> how do we minimize the residuals, <span class="math inline">\(\epsilon_i = y_i - (\alpha + \beta x_i)\)</span>? In other words, how do we minimize the sum of the squared errors?</p>
<blockquote class="blockquote">
<p>insert image of vertical line from regression line to point, label it e_i</p>
</blockquote>
<p>Given:</p>
<ul>
<li>
<span class="math inline">\(y_i\)</span>: the actual value of the data point</li>
<li>
<span class="math inline">\(\hat{y_i}\)</span>: the predicted value of the <span class="math inline">\(i^{th}\)</span> data point</li>
</ul>
<p><span class="math inline">\(SSE = \sum\limits_{i=1}^{n} (y_i - \hat{y_i})^2\)</span></p>
<blockquote class="blockquote">
<p>the point-estimates (single value estimated from the data) of the slope and intercept parameters are called the least-squares estimates, and are defined to be the values that minimize the SSE. The SSE can be thought of as a measure of how much variation in <span class="math inline">\(Y\)</span> is left unexplained by the model.</p>
</blockquote>
</section><section id="how-we-find-the-parameter-estimates" class="level2"><h2 class="anchored" data-anchor-id="how-we-find-the-parameter-estimates">How we Find the Parameter Estimates?</h2>
<p><span class="math inline">\(SSE = \sum\limits_{i=1}^{n} (y_i - \hat{y_i})^2\)</span></p>
<p><span class="math inline">\(= \sum\limits_{i=1}^{n} (y_i - (\alpha - \beta x_i))^2\)</span></p>
<p><strong>After making this substitution, compute…</strong></p>
<ul>
<li><span class="math inline">\(\frac{\partial SSE}{\partial \alpha} = 0\)</span></li>
<li><span class="math inline">\(\frac{\partial SSE}{\partial \beta} = 0\)</span></li>
</ul>
<p><strong>Which yield the following solutions, respectively…</strong></p>
<ul>
<li><span class="math inline">\(\alpha = \bar{y} - \beta \bar{x}\)</span></li>
<li><span class="math inline">\(\beta = \frac{\bar{xy} - \bar{x} \bar{y}}{\bar{x^2} - (\bar{x})^2}\)</span></li>
</ul></section><section id="estimating-the-variance" class="level2"><h2 class="anchored" data-anchor-id="estimating-the-variance">Estimating the Variance</h2>
<p>Given that the parameter <span class="math inline">\(\sigma^2\)</span> determines the spread of the data about the true regression line, our estimate of the variance is <span class="math inline">\(\hat{\sigma}^2\)</span>, which is equivalent to:</p>
<p><span class="math inline">\(\hat{\sigma}^2 = \frac{SSE}{n-2}\)</span></p>
</section><section id="coefficient-of-determination" class="level2"><h2 class="anchored" data-anchor-id="coefficient-of-determination">Coefficient of Determination</h2>
<p>The coefficient of determination, <span class="math inline">\(R^2\)</span>, quantifies how well the model explains the data. <span class="math inline">\(R^2\)</span> ranges from <span class="math inline">\(0\)</span> to <span class="math inline">\(1\)</span>.</p>
<p>The regression sum of squares is given by:</p>
<p><span class="math inline">\(SSR = \sum\limits_{i=1}^n (\hat{y_i} - \bar{y})^2\)</span></p>
<p>and gives a sense of how much variation in <span class="math inline">\(Y\)</span> is explained by our model.</p>
<p>A quantitative measure of the total amount of variation in observed <span class="math inline">\(Y\)</span> values is given by the total sum of squares:</p>
<p><span class="math inline">\(SST = \sum\limits_{i=1}^n (y_i - \bar{y})^2\)</span></p>
<p>SST is what we would get if we used the mean of the data as our model.</p>
<p>Note that the sum of squared deviations about the least-squares line is smaller than the sum of squared deviations about nay other line.</p>
<p><span class="math inline">\(SSE \leq SST\)</span></p>
<blockquote class="blockquote">
<p>Include image of the three measures.</p>
</blockquote>
<p><strong><span class="math inline">\(R^2\)</span></strong></p>
<p>Therefore, the ratio of <span class="math inline">\(\frac{SSE}{SST}\)</span> is the proportion of the total variation in the data (SST) that cannot be explained by the SLR model (SSE). So we define the coefficient of determination <span class="math inline">\(R^2\)</span> to be the proportion of variance that can be explained by the model.</p>
<p><span class="math inline">\(R^2\)</span> has a magnitude between <span class="math inline">\(0\)</span> and <span class="math inline">\(1\)</span>, with the closer to <span class="math inline">\(1\)</span> be the better (i.e.&nbsp;the higher the number the more of the variation that can be explained by the model).</p>
<p><span class="math inline">\(R^2 = 1 - \frac{SSE}{SST}\)</span></p>
</section><section id="slope-distribution" class="level2"><h2 class="anchored" data-anchor-id="slope-distribution">Slope Distribution</h2>
<p><strong>Distribution</strong></p>
<p><span class="math inline">\(\hat{\beta} \sim N(\beta, \frac{\sigma^2}{\sum_{i=1}^n (x_i - \bar{x})^2})\)</span></p>
<p><span class="math inline">\(SE(\hat{\beta}) = \frac{\hat{\sigma}}{\sqrt{\sum_{i=1}^n (x_i - \bar{x})^2}}\)</span></p>
<p><strong>Hypothesis Tests</strong></p>
<p><span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta = 0\)</span></p>
<p><span class="math inline">\(H_A\)</span>: <span class="math inline">\(\beta \neq 0\)</span></p>
<p><strong>Confidence Intervals</strong></p>
<p><span class="math inline">\(\hat{\beta} \pm t_{\alpha / 2, df = n-2} SE(\hat{\beta})\)</span></p>
<blockquote class="blockquote">
<p>Note the statistic from the confidence interval, we use t-tests for the coefficients (i.e.&nbsp;individul coefficients for linear regression models). Specifically, used in finding if a feature has an effect on the response. In the case of a small enough p-value, we can reject the null hypothesis in favor of the alternative hypothesis which means there is statistical evidence that the associated feature (variable) has an effect on the response variable.</p>
</blockquote>
</section><section id="summary-of-slr" class="level2"><h2 class="anchored" data-anchor-id="summary-of-slr">SUMMARY OF SLR</h2>
<section id="main-formula" class="level3"><h3 class="anchored" data-anchor-id="main-formula">Main Formula</h3>
<p><span class="math inline">\(Y = \alpha + \beta X + \epsilon\)</span></p>
</section><section id="variance-slope-distribution-betas" class="level3"><h3 class="anchored" data-anchor-id="variance-slope-distribution-betas">Variance &amp; Slope Distribution (<span class="math inline">\(\beta\)</span>s)</h3>
<p><span class="math inline">\(\hat{\sigma}^2 = \frac{SSE}{n-2}\)</span></p>
<p><span class="math inline">\(SE(\hat{\beta}) = \frac{\hat{\sigma}}{\sqrt{\sum_{i=1}^n (x_i - \bar{x})^2}}\)</span></p>
</section><section id="ci-for-t-tests-on-beta" class="level3"><h3 class="anchored" data-anchor-id="ci-for-t-tests-on-beta">CI for t-tests on <span class="math inline">\(\beta\)</span>
</h3>
<p><span class="math inline">\(\hat{\beta} \pm t_{\alpha / 2, df = n-2} SE(\hat{\beta})\)</span></p>
</section><section id="coefficient-of-determination-1" class="level3"><h3 class="anchored" data-anchor-id="coefficient-of-determination-1">Coefficient of Determination</h3>
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead><tr class="header">
<th></th>
<th>SSE</th>
<th>SSR</th>
<th>SST</th>
<th><span class="math inline">\(R^2\)</span></th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Description</td>
<td>Measure of how much variation in <span class="math inline">\(Y\)</span> is left unexplained by the model</td>
<td>How much variation in <span class="math inline">\(Y\)</span> is explained by our model</td>
<td>Total amount of variation in observed <span class="math inline">\(Y\)</span> values (what we would get if we used the mean of the data as our model)</td>
<td>The proportion of variance that can be explained by the model</td>
</tr>
<tr class="even">
<td>Formula</td>
<td><span class="math inline">\(\sum\limits_{i=1}^{n} (y_i - \hat{y_i})^2\)</span></td>
<td><span class="math inline">\(\sum\limits_{i=1}^n (\hat{y_i} - \bar{y})^2\)</span></td>
<td><span class="math inline">\(\sum\limits_{i=1}^n (y_i - \bar{y})^2\)</span></td>
<td><span class="math inline">\(1 - \frac{SSE}{SST}\)</span></td>
</tr>
</tbody>
</table>
<p><strong>The closer to 1 <span class="math inline">\(R^2\)</span> is, the better the model fits the data.</strong></p>
</section></section><section id="workflow-for-simple-linear-regression" class="level2"><h2 class="anchored" data-anchor-id="workflow-for-simple-linear-regression">Workflow for Simple Linear Regression</h2>
<ol type="1">
<li>Plot the data as a scatter plot</li>
</ol>
<ol type="a">
<li>Does linearity seem appropriate?</li>
<li>Compute and overlay best-fit line</li>
</ol>
<ol start="2" type="1">
<li>Consider assumptions in SLR</li>
</ol>
<ol type="a">
<li>Plot a histogram of the residuals (are they normal?): <strong>WANT NORMAL</strong>
</li>
<li>Plot the residuals against x (are they changing?): <strong>WANT RANDOM</strong>
</li>
</ol>
<blockquote class="blockquote">
<p>Include Plots</p>
</blockquote>
</section><section id="simple-linear-regression-in-r" class="level2"><h2 class="anchored" data-anchor-id="simple-linear-regression-in-r">Simple Linear Regression in R</h2>
<p>The following functions are paramount in implementing and interpreting simple linear regression in R:</p>
<ul>
<li><code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code></li>
<li><code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code></li>
</ul>
<blockquote class="blockquote">
<p>Load Library</p>
</blockquote>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># import libraries</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<blockquote class="blockquote">
<p>Load Data (use txhousing from built in data)</p>
</blockquote>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="va">txhousing</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 9
  city     year month sales   volume median listings inventory  date
  &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;dbl&gt;
1 Abilene  2000     1    72  5380000  71400      701       6.3 2000 
2 Abilene  2000     2    98  6505000  58700      746       6.6 2000.
3 Abilene  2000     3   130  9285000  58100      784       6.8 2000.
4 Abilene  2000     4    98  9730000  68600      785       6.9 2000.
5 Abilene  2000     5   141 10590000  67300      794       6.8 2000.
6 Abilene  2000     6   156 13910000  66900      780       6.6 2000.</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Create a simple linear regression model to see if we can explain and predict volume from listings</p>
</blockquote>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">slr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">volume</span> <span class="op">~</span> <span class="va">listings</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">slr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = volume ~ listings, data = df)

Residuals:
       Min         1Q     Median         3Q        Max 
-704067392  -27385680  -12084812    -951885 1686521981 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -1501601.1  1750052.1  -0.858    0.391    
listings       36990.0      258.1 143.319   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 130500000 on 7174 degrees of freedom
  (1426 observations deleted due to missingness)
Multiple R-squared:  0.7411,    Adjusted R-squared:  0.7411 
F-statistic: 2.054e+04 on 1 and 7174 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>From this summary, we can see that <code>listings</code> is a statistically significant factor (low p-value) and that the <span class="math inline">\(R^2\)</span> for the model is somewhat acceptable at <span class="math inline">\(0.7411\)</span>. Although the intercept being negative does raise some concern, this would mean that for a time period with <span class="math inline">\(0\)</span> <code>listings</code>, we would get a negative <code>volume</code>. The model also says that for each new <code>listing</code>, we can expect the <code>volume</code> to increase by <span class="math inline">\(36990\)</span>.</p>
<hr></section></section><section id="multiple-linear-regression" class="level1"><h1>Multiple Linear Regression</h1>
<p>We can extend the <strong>simple linear regression model</strong> to accommodate more variables. <em>Note that we’ll now refer to <span class="math inline">\(\alpha\)</span> as <span class="math inline">\(\beta_0\)</span></em>.</p>
<p>The main vector model can be represented as:</p>
<p><span class="math inline">\(Y = \beta_0 + B_1 X_1 + \dots + B_p X_p + \epsilon\)</span></p>
<p>where for each of the <span class="math inline">\(n\)</span> data points (each vector has the same number of data points), we assume for <span class="math inline">\(i = 1, \dots, n\)</span>, the <span class="math inline">\(i^{th}\)</span> response variable is represented as:</p>
<p><span class="math inline">\(y_i = \beta_0 + B_1 x_{i, 1} + \dots + B_p x_{i, p} + \epsilon_i\)</span></p>
<section id="matrix-algebra-applications-solutions" class="level2"><h2 class="anchored" data-anchor-id="matrix-algebra-applications-solutions">Matrix Algebra Applications &amp; Solutions</h2>
<p>If we have a perfectly square <span class="math inline">\(X\)</span> matrix, then we can solve for <span class="math inline">\(\beta\)</span> via:</p>
<p><span class="math inline">\(Y = X \beta \rightarrow X^{-1} Y = \beta\)</span>.</p>
<p>However, we can almost <strong>guarantee</strong> that <span class="math inline">\(X\)</span> will not be square. Look at this following linear algebra application:</p>
<blockquote class="blockquote">
<p>Given a matrix <span class="math inline">\(A\)</span> of any dimensions, both <span class="math inline">\(A^TA\)</span> and <span class="math inline">\(AA^T\)</span> will result in square matrices.</p>
</blockquote>
<p>Therefore, given <span class="math inline">\(Y = X \beta\)</span>, we can solve via the following:</p>
<p><span class="math inline">\((X^TX)^{-1}X^TY = \beta\)</span></p>
</section><section id="interpreting-mlr" class="level2"><h2 class="anchored" data-anchor-id="interpreting-mlr">Interpreting MLR</h2>
<p>Given <span class="math inline">\(y_i = \beta_0 + B_1 x_{i, 1} + \dots + B_p x_{i, p} + \epsilon_i\)</span>, parameter <span class="math inline">\(\beta_k\)</span> is the expected change in the response associated with a unit change in the value of feature <span class="math inline">\(x_k\)</span> while all of the other features are held fixed.</p>
</section><section id="quantifying-goodness-of-fit" class="level2"><h2 class="anchored" data-anchor-id="quantifying-goodness-of-fit">Quantifying Goodness of Fit</h2>
<section id="r2-vs.-r_a2" class="level3"><h3 class="anchored" data-anchor-id="r2-vs.-r_a2">
<span class="math inline">\(R^2\)</span> vs.&nbsp;<span class="math inline">\(R_a^2\)</span>
</h3>
<p>Like in SLR, we can also calculate measures like <strong>SSE</strong>, <strong>SST</strong>, and <strong><span class="math inline">\(R^2\)</span></strong> for MLR.</p>
<ul>
<li><span class="math inline">\(SSE = \sum\limits_{i=1}^n (y_i - \hat{y_i})^2 = \sum\limits_{i=1}^n (y_i - (\beta_0 + B_1 x_{i, 1} + \dots + B_p x_{i, p}))^2\)</span></li>
<li><span class="math inline">\(SST = \sum\limits_{i=1}^n (y_i - \bar{y})^2\)</span></li>
<li><span class="math inline">\(R^2 = 1 - \frac{SSE}{SST}\)</span></li>
</ul>
<p>Although we can calculate <span class="math inline">\(R^2\)</span> for an MLR model, we run into the issue of multiple comparisons. The <strong>Adjusted <span class="math inline">\(R^2\)</span></strong>, <span class="math inline">\(R_a^2\)</span>, is a better indicator of goodness of fit for MLR models. The adjusted version penalizes for having too many features that are not reducing SSE.</p>
<p><span class="math inline">\(R_a^2 = 1 - \frac{SSE/(n-p-1)}{SST/(n-1)}\)</span></p>
</section><section id="covariance-correlation" class="level3"><h3 class="anchored" data-anchor-id="covariance-correlation">Covariance &amp; Correlation</h3>
<p>We can discover relationships among features by performing a correlation analysis. If the value of one feature changes, how will this affect the other features.</p>
<p>Traditionally, these measurements are calculated via:</p>
<ul>
<li>Covariance: <span class="math inline">\(Cov(X, Y) = E[(X - E[X])(Y -E[Y])]\)</span>
</li>
<li>Correlation (Pearson’s): <span class="math inline">\(\rho(X, Y) = \frac{Cov(X, Y)}{\sqrt{Var(X) Var(Y)}}\)</span>
</li>
</ul>
<p>However, in an MLR, we estimate these relationships using formulas analogous to the sample variance.</p>
<ul>
<li>Sample Covariance: <span class="math inline">\(S^2_{XY} = \frac{1}{n-1} \sum\limits_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})\)</span>
</li>
<li>Sample Correlation <span class="math inline">\(\hat{\rho}(X &lt; Y) = \frac{S^2_{XY}}{\sqrt{S^2_{X}S^2_{Y}}}\)</span>
</li>
</ul>
<p><em>where <span class="math inline">\(S^2_{X}\)</span> and <span class="math inline">\(S^2_{Y}\)</span> are the variances for <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, respectively</em>.</p>
</section></section><section id="individual-t-tests" class="level2"><h2 class="anchored" data-anchor-id="individual-t-tests">Individual t-tests</h2>
<p>Suppose we want to test:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_j = c\)</span>
</li>
<li>
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(\beta_j \neq c\)</span>
</li>
</ul>
<p>for some <span class="math inline">\(c \in \mathbb{R}\)</span>.</p>
<p>We would use a t-test with the test statistic:</p>
<p><span class="math inline">\(t_{stat} = \frac{\hat{\beta_j} - c}{SE(\hat{\beta_j})}\)</span></p>
<p>Recall our CI for <span class="math inline">\(\beta\)</span>:</p>
<p>CI: <span class="math inline">\(\hat{\beta} \pm t_{\alpha/2, df = n - 2} \frac{\hat{\sigma}}{\sqrt{\sum_{i=1}^n(x_i - \bar{x})^2}}\)</span></p>
<p><span class="math inline">\(= \hat{\beta} \pm t_{\alpha/2, df = n - 2} \hat{SE(\hat{\beta_j})}\)</span></p>
<p>Compare the test statistic with the t-test critical value (<span class="math inline">\(t_{\alpha/2, df = n - 2}\)</span>) and proceed from there.</p>
<section id="mlr-in-r-individual-t-test-output-from-summary" class="level3"><h3 class="anchored" data-anchor-id="mlr-in-r-individual-t-test-output-from-summary">MLR in R: Individual t-test Output from <code>summary</code>
</h3>
<blockquote class="blockquote">
<p>From same dataset used in SLR, create MLR. Note: we can specify all variables like <code>y ~ x1 + x2 + ... + xn</code>, or we can call all of the variables besides the response variable by using <code>.</code>.</p>
</blockquote>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">volume</span> <span class="op">~</span> <span class="va">month</span> <span class="op">+</span> <span class="va">sales</span> <span class="op">+</span> <span class="va">listings</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = volume ~ month + sales + listings, data = df)

Residuals:
       Min         1Q     Median         3Q        Max 
-425617453   -8326819    1919907    8285352  451201576 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -7064965.5  1055382.2  -6.694 2.33e-11 ***
month        -103150.3   141167.5  -0.731    0.465    
sales         274509.7     1078.4 254.559  &lt; 2e-16 ***
listings      -12218.7      209.8 -58.251  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 41190000 on 7172 degrees of freedom
  (1426 observations deleted due to missingness)
Multiple R-squared:  0.9742,    Adjusted R-squared:  0.9742 
F-statistic: 9.035e+04 on 3 and 7172 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>In the above summary printout, note that:</p>
<ul>
<li>Std. Error = <span class="math inline">\(SE(\hat{\beta})\)</span>
</li>
<li>t value: <span class="math inline">\(t_{stat}\)</span>
</li>
<li>Pr(&gt;|t|): p-value</li>
</ul>
<p>Note that the <code><a href="https://rdrr.io/r/stats/lm.html">lm()</a></code> and <code>summary</code> functions asume a hypothesis test of:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_j = 0\)</span>
</li>
<li>
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(\beta_j \neq 0\)</span>
</li>
</ul>
<p>So, depending on the significance level we had set beforehand, we either reject the null hypothesis in favor of the alternative hypothesis or fail to reject the null hypothesis. In the case of a small <em>enough</em> p-value, we can reject the null hypothesis in favor of the alternative hypothesis which means there is statistical evidence that the associated feature (variable) has an effect on the response variable.</p>
</section><section id="type-i-errors-in-multiple-t-tests" class="level3"><h3 class="anchored" data-anchor-id="type-i-errors-in-multiple-t-tests">Type I Errors in Multiple t-tests</h3>
<blockquote class="blockquote">
<p>However, it is not a good idea to conduct several t-tests at a time!</p>
</blockquote>
<p><strong>Example</strong>: Suppose that we conduct 10 hypothesis tests at significance level <span class="math inline">\(\alpha = 0.05\)</span>. So, the probability of type 1 error is 0.05 for any individual test.</p>
<p>What is the probability of a type I error ocurring in at least one of these 10 tests?</p>
<p><span class="math inline">\(P(\text{at least 1 type I error}) = 1 - P(\text{no type I error})\)</span></p>
<p><span class="math inline">\(= 1 - (0.95)^{10}\)</span></p>
<p><span class="math inline">\(\approx 0.40\)</span></p>
<p>Which is high!</p>
</section></section><section id="multicollinearity-collinearity-non-identifiability" class="level2"><h2 class="anchored" data-anchor-id="multicollinearity-collinearity-non-identifiability">Multicollinearity / Collinearity / Non-Identifiability</h2>
<p>Multicollinearity, also known non-identifiability, can occur when there is linear dependence between columns of data. “Strict” non-identifiability occurs with true linear dependence and can be diagnosed with <code>NA</code> rows for MLR coefficients in a given <code>summary</code>, is <strong>rare</strong>. “Near” non-identifiability is less rare but can be tricky to diagnose. One method of diagnosing “near” collinearity is to recognize “<em>fishy</em>” coefficients, such as negatives when expecting positive.</p>
<p>This is a concern because linear dependence causes non-invertibility in the matrices <span class="math inline">\(X^TX\)</span> and <span class="math inline">\(XX^T\)</span> for any given matrix <span class="math inline">\(X\)</span>. This is disruptive in creating MLR models.</p>
</section><section id="f-test" class="level2"><h2 class="anchored" data-anchor-id="f-test">F-test</h2>
<p>How do control the <strong>overall</strong> type I error rate when we need to test whether to drop several predictors from a model. We can use a simultaneous test, the <strong>F-test</strong>.</p>
<p>Consider two different models from a dataset with <span class="math inline">\(p\)</span> features:</p>
<ul>
<li>Full Model: <span class="math inline">\(\Omega\)</span>: <span class="math inline">\(Y = \beta_0 + \beta_1 X_1 + \dots + \beta_p X_p\)</span>
</li>
<li>Reduced Model: <span class="math inline">\(\omega\)</span>: <span class="math inline">\(Y = \beta_0 + \beta_1 X_1 + \dots + \beta_q X_q\)</span>, where <span class="math inline">\(q &lt; p\)</span>
</li>
</ul>
<p>We can consider testing the following hypothesis:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\omega\)</span> is sufficient</li>
<li>
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(\omega\)</span> is not sufficient</li>
</ul>
<section id="the-full-f-test" class="level3"><h3 class="anchored" data-anchor-id="the-full-f-test">The Full F-test</h3>
<p>The null hypothesis is the <strong>most reduced model possible</strong></p>
<p>The idea:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(y_i = \beta_0 + \epsilon_i\)</span>
</li>
<li>
<span class="math inline">\(H_A\)</span>: at least 1 <span class="math inline">\(B_j \neq 0\)</span>, where <span class="math inline">\(j = 1, \dots, p\)</span>
</li>
</ul>
<p>In other words, we want to check whether ALL coefficients are 0:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = \beta_2 = \dots = \beta_p = 0\)</span>
</li>
<li>
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(B_k \neq 0\)</span> for at least one value of <span class="math inline">\(k = 1, \dots, p\)</span>
</li>
</ul>
<blockquote class="blockquote">
<p>The null hypothesis in the MLR case says that there is no useful linear relationship between <span class="math inline">\(y\)</span> and any of the <span class="math inline">\(p\)</span> predictors.</p>
</blockquote>
<p>The null hypothesis essentially states that there is no useful linear relationship between the response and any of the predictors. A small enough p-value suggests strong evidence against the null hypothesis, or in other words the model is better than the most reduced model possible. Useful in multiple linear regression (MLR) where the individual t-tests are suggesting evidence against the null hypothesis may result in type I errors.</p>
<p><span class="math inline">\(F_{stat} = \frac{\frac{SST - SSE}{p}}{\frac{SSE}{n-p-1}}\)</span></p>
<p>where <span class="math inline">\(p = df_{SST} - df_{SSE}\)</span></p>
<p>The <span class="math inline">\(F_{stat}\)</span> is a measure of how much better our model is than just using the mean.</p>
<blockquote class="blockquote">
<p>If <span class="math inline">\(H_0\)</span> were true, then we would expect to see <span class="math inline">\(F_{stat} \approx 1\)</span>. In other words, if we see an <span class="math inline">\(F_{stat}\)</span> around 1, we will likely fail to reject the null hypothesis.</p>
</blockquote>
<blockquote class="blockquote">
<p>If <span class="math inline">\(H_A\)</span> were true, then <span class="math inline">\(SSE &lt; SST \rightarrow F_{stat} &gt;&gt; 1\)</span></p>
</blockquote>
</section><section id="the-partial-f-test" class="level3"><h3 class="anchored" data-anchor-id="the-partial-f-test">The Partial F-test</h3>
<p>Suppose we have the following setup:</p>
<ul>
<li>Full Model: <span class="math inline">\(y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \beta_3 x_3 + \beta_4 x_4\)</span>
</li>
<li>Reduced Model: <span class="math inline">\(y = \beta_0 + \beta_2 x_2 + \beta_4 x_4\)</span>
</li>
</ul>
<p>Are the missing features important, or are we okay with the reduced model?</p>
<p><strong>Hypothesis Test for the Partial F-test</strong>:</p>
<ul>
<li>
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1 = \beta_3 = 0\)</span>
</li>
<li>
<span class="math inline">\(H_A\)</span>: at least one of <span class="math inline">\(\beta_1\)</span>, <span class="math inline">\(\beta_3\)</span> <span class="math inline">\(\neq 0\)</span>
</li>
</ul>
<p><strong>Strategy: fit the full and reduced models, then determine if the difference in performance is real or just due to chance.</strong></p>
<p>Let’s examine some measurements from the <em>full</em> and <em>reduced</em> models.</p>
<ul>
<li>
<span class="math inline">\(SSE_{full}\)</span>: variation unexplained by the full model</li>
<li>
<span class="math inline">\(SSE_{reduced}\)</span>: variation unexplained by the reduced model</li>
</ul>
<p>Intuitively, if <span class="math inline">\(SSE_{full}\)</span> is much smaller than <span class="math inline">\(SSE_{reduced}\)</span>, the full model fits the data much better than the reduced model. Therefore, the appropriate test statistic should depend on the difference between the unexplained variation.</p>
<p>Give a full model with <span class="math inline">\(p\)</span> features and a reduced model with <span class="math inline">\(k\)</span> features:</p>
<p><span class="math inline">\(F_{stat-partial} = \frac{(SSE_{reduced} - SSE_{full}) / p - k}{SSE_{full} / (n-p-1)} \sim F_{p-k, n-p-1}\)</span></p>
<p>with the rejection region: <span class="math inline">\(F \geq F_{\alpha, p-k, n-p-1}\)</span></p>
<p><em>Note that <span class="math inline">\(p-k\)</span> comes from the differences in degrees of freedom</em>:</p>
<p><span class="math inline">\(df_{reduced} - df_{full} = (n-k-1) - (n-p-1) = p - k\)</span></p>
<blockquote class="blockquote">
<p>Large <span class="math inline">\(F_{stat} \rightarrow\)</span> Low P-Value from F-distribution <span class="math inline">\(\rightarrow\)</span> Well Fitting Model</p>
</blockquote>
<p><strong>Principal of Parsimony</strong>: The principle that the most acceptable explanation of an occurrence, phenomenon, or event is the simplest, involving the fewest entities, assumptions, or changes.</p>
<p>We’re striving to create an MLR model which explains the variation in the data with relatively few features that are easily interpreted.</p>
</section></section><section id="feature-selection" class="level2"><h2 class="anchored" data-anchor-id="feature-selection">Feature Selection</h2>
<p>The number of models to test can exponentially increase with the number of features.</p>
<p>Given <span class="math inline">\(p\)</span> features, there are <span class="math inline">\(\sum\limits_{i=0}^p = 2^p\)</span> possible models.</p>
<p>What are some ways we can reduce the impossible amount of models to try?</p>
<section id="forward-selection" class="level3"><h3 class="anchored" data-anchor-id="forward-selection">Forward Selection</h3>
<p>A greedy algorithm for adding features.</p>
<ol type="1">
<li>Fit a null model with an intercept but no slopes</li>
<li>Fit p individual SLR models - one for each possible feature. Add to the null model the one that improves the performance the most, based on some measure (i.e.&nbsp;decreases SSE the most, increases F-statistic the most, etc.)</li>
<li>Fit (p - 1) MLR models - one for each of the remaining features along with the feature we isolated from step 2. Add the one that improves model performance the most.</li>
<li>Repeat until some stopping criterion is reached (i.e.&nbsp;some threshold SSE, or some fixed number of features, etc.)</li>
</ol></section><section id="backward-selection" class="level3"><h3 class="anchored" data-anchor-id="backward-selection">Backward Selection</h3>
<p>A greedy algorithm for removing features.</p>
<ol type="1">
<li>Fit model with available features.</li>
<li>Remove the feature with the largest p-value (i.e.&nbsp;the least significant feature).</li>
<li>Repeat until some stopping criterion is reached (i.e.&nbsp;some threshold SSE, or some fixed number of features, etc.).</li>
</ol>
<hr></section></section></section><section id="further-interpretations-and-r-examples" class="level1"><h1>Further Interpretations and R Examples</h1>
<section id="basic-interpretations" class="level2"><h2 class="anchored" data-anchor-id="basic-interpretations">Basic Interpretations</h2>
<p>Let’s recreate our MLR from earlier:</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">volume</span> <span class="op">~</span> <span class="va">month</span> <span class="op">+</span> <span class="va">sales</span> <span class="op">+</span> <span class="va">listings</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><code>summary</code></p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = volume ~ month + sales + listings, data = df)

Residuals:
       Min         1Q     Median         3Q        Max 
-425617453   -8326819    1919907    8285352  451201576 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -7064965.5  1055382.2  -6.694 2.33e-11 ***
month        -103150.3   141167.5  -0.731    0.465    
sales         274509.7     1078.4 254.559  &lt; 2e-16 ***
listings      -12218.7      209.8 -58.251  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 41190000 on 7172 degrees of freedom
  (1426 observations deleted due to missingness)
Multiple R-squared:  0.9742,    Adjusted R-squared:  0.9742 
F-statistic: 9.035e+04 on 3 and 7172 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><code>anova</code></p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: volume
            Df     Sum Sq    Mean Sq    F value    Pr(&gt;F)    
month        1 1.5469e+17 1.5469e+17     91.194 &lt; 2.2e-16 ***
sales        1 4.5387e+20 4.5387e+20 267563.442 &lt; 2.2e-16 ***
listings     1 5.7558e+18 5.7558e+18   3393.153 &lt; 2.2e-16 ***
Residuals 7172 1.2166e+19 1.6963e+15                         
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>The anova table gives us:</p>
<ul>
<li>
<code>Df</code>: degrees of freedom</li>
<li>
<code>Sum Sq</code>: SSE (for Residuals)</li>
<li>
<code>Sum Sq</code>: SST (total column)</li>
<li>
<code>Mean Sq</code>: SSR (for features)</li>
</ul>
<p><code>residuals</code></p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_density.html">geom_density</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="linear_regression_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span><span class="op">)</span><span class="op">)</span>, y<span class="op">=</span><span class="fu"><a href="https://rdrr.io/r/stats/residuals.html">residuals</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output-display">
<div>
<figure class="figure"><p><img src="linear_regression_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Don’t run, but this will return the predicted response values:</strong> <code>fitted(mlr)</code></p>
<hr></section><section id="f-tests" class="level2"><h2 class="anchored" data-anchor-id="f-tests">F-tests</h2>
<p><strong>Let’s check out the F-tests.</strong></p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = volume ~ month + sales + listings, data = df)

Residuals:
       Min         1Q     Median         3Q        Max 
-425617453   -8326819    1919907    8285352  451201576 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -7064965.5  1055382.2  -6.694 2.33e-11 ***
month        -103150.3   141167.5  -0.731    0.465    
sales         274509.7     1078.4 254.559  &lt; 2e-16 ***
listings      -12218.7      209.8 -58.251  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 41190000 on 7172 degrees of freedom
  (1426 observations deleted due to missingness)
Multiple R-squared:  0.9742,    Adjusted R-squared:  0.9742 
F-statistic: 9.035e+04 on 3 and 7172 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Here we notice that the individual t-tests are <em>statistically significant</em>, however be wary of type I errors. However, we can notice that the t-test associated with month is not significant, suggesting there is no evidence that parameter isn’t zero. Let’s check out the F-stat, which does have a high value with a low p-value associated with it. This is indicative of strong evidence that at least one of the <span class="math inline">\(B_{k}\)</span>s are not <span class="math inline">\(0\)</span>.</p>
<p>Let’s test a model removing month with a partial f-test.</p>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">mlr_reduced</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/lm.html">lm</a></span><span class="op">(</span><span class="va">volume</span> <span class="op">~</span> <span class="va">sales</span> <span class="op">+</span> <span class="va">listings</span>, data <span class="op">=</span> <span class="va">df</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold"><summary>Code</summary><div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/stats/anova.html">anova</a></span><span class="op">(</span><span class="va">mlr_reduced</span>, <span class="va">mlr</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details><div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Model 1: volume ~ sales + listings
Model 2: volume ~ month + sales + listings
  Res.Df        RSS Df  Sum of Sq      F Pr(&gt;F)
1   7173 1.2167e+19                            
2   7172 1.2166e+19  1 9.0568e+14 0.5339  0.465</code></pre>
</div>
</div>
<p>The p-value for the f-test is very large, indicate that we don’t have enough evidence to reject the null hypothesis, which means that the reduced model is likely sufficient.</p>


</section></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p><a href="https://clickityklein.github.io/Carl-Klein/">About Carl Klein</a></p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>


</body></html>